# Generated by Django 3.2.9 on 2021-12-06 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='passwordSalt',
            field=models.CharField(default=None, max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=256),
        ),
    ]
