# Generated by Django 3.2.9 on 2021-12-17 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20211217_1232'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
